CREATE TABLE users
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    display_name VARCHAR(100) NOT NULL,
    created_at_utc TIMESTAMP NOT NULL
);

CREATE TABLE friend_requests
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id INTEGER NOT NULL REFERENCES users(id),
    recipient_id INTEGER NOT NULL REFERENCES users(id),
    status VARCHAR(20) NOT NULL,
    created_at_utc TIMESTAMP NOT NULL,
    responded_at_utc TIMESTAMP NULL
);

CREATE TABLE conversations
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind VARCHAR(20) NOT NULL,
    created_at_utc TIMESTAMP NOT NULL
);

CREATE TABLE conversation_members
(
    conversation_id INTEGER NOT NULL REFERENCES conversations(id),
    user_id INTEGER NOT NULL REFERENCES users(id),
    joined_at_utc TIMESTAMP NOT NULL,
    PRIMARY KEY (conversation_id, user_id)
);

CREATE TABLE messages
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id INTEGER NOT NULL REFERENCES conversations(id),
    sender_id INTEGER NOT NULL REFERENCES users(id),
    body VARCHAR(1000) NOT NULL,
    media_url VARCHAR(255) NOT NULL,
    media_type VARCHAR(50) NOT NULL,
    created_at_utc TIMESTAMP NOT NULL
);

CREATE TABLE posts
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id INTEGER NOT NULL REFERENCES users(id),
    caption VARCHAR(500) NOT NULL,
    media_url VARCHAR(255) NOT NULL,
    created_at_utc TIMESTAMP NOT NULL
);
